%YAML:1.0

#common parameters
imu_topic: "/Sensor/AHRS"
image_topic: "/web_cameras/right/image_raw"
output_path: "/home/ubuntu/VINS-Mono-Benchmark/output/"

#camera calibration 
model_type: PINHOLE
camera_name: camera

image_width: 704
image_height: 394 #576
distortion_parameters: 
   k1: -0.400271652001085
   k2: 0.136408571231384
   p1: 0.00132442150195077
   p2: -0.00181578465110289
projection_parameters:
   fx: 602.0 #453.756242626283
   fy: 601.33 #661.664002287457
   cx: 349.618669407031
   cy: 211.14

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.                        
#If you choose 0 or 1, you should write down the following matrix.

extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.9930, 0.1066, -0.0515,
         0.1080, -0.9938, 0.0263,
         -0.0484, -0.0316, -0.9983]

extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [-0.360, 0.294, 0.0]

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 0             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 9.5807216287427371e-02          # accelerometer measurement noise standard deviation. #0.2
gyr_n: 1.9678487995857213e-02        # gyroscope measurement noise standard deviation.     #0.05
acc_w: 3.1066007351086708e-05       # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 2.9002150032461746e-05      # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.8046     # gravity magnitude

#loop closure parameters
loop_closure: 1                 # start loop closure
load_previous_pose_graph: 0     # load and reuse previous pose graph; load from 'pose_graph_save_path'
fast_relocalization: 0      # useful in real-time and large project
pose_graph_save_path: "/home/ubuntu/VINS-Mono-Benchmark/output/pose_graph/" # save and load path

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: -1.42                         # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 0                  # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0               # unit: s. rolling shutter read out time per frame (from data sheet). 

#visualization parameters
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
visualize_imu_forward: 0        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ